services:
  - type: web
    plan: free
    name: django-app
    runtime: python
    repo: https://github.com/render-examples/django.git
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-app-db
          property: connectionString
  - type: web
    plan: free
    name: django-app2
    runtime: python
    repo: https://github.com/render-examples/django.git
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-app-db
          property: connectionString

databases:
  - name: django-app-db
    plan: free

envVars:
  - key: API_BASE_URL
    value: https://api.example.com
  - key: STRIPE_API_KEY
    sync: false
