services:
  - type: web
    plan: pro
    previewPlan: pro
    name: og-tag-test
    runtime: node
    repo: https://github.com/mauricioschneider/render-og-tag-test.git
    buildCommand: 'npm install'
    startCommand: 'npm start'
    previews:
      generation: automatic